### ISSUE TITLE
OOM problem at fine-tuning stage

### ISSUE THREAD

**Issue by yihu-dev** [prov-gigapath/prov-gigapath#12]
Hi,

When I try the Slide-Level Fine-Tuning example suing PANDA dataset, it works smoothly and get expected results.
But on TCGA-lung luad dataset, I got OOM problem for some folds.
I have prepared the data as described in your paper such as: select largest slides if a patient has multiple slides then create 10 folds.

> Dataset has been initialized!
Dataset has been initialized!
Dataset has been initialized!
dilated_ratio:  [1, 2, 4, 8, 16]
segment_length:  [1024, 4870, 23170, 110217, 524288]
Number of trainable LongNet parameters:  85148160
Global Pooling: False
slide_encoder.pth: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 345M/345M [00:01<00:00, 222MB/s]
 Successfully Loaded Pretrained GigaPath model from hf_hub:prov-gigapath/prov-gigapath 
Using fp16 training
Training on 365 samples
Validating on 46 samples
Testing on 46 samples
Training starts!
Epoch: 0
Epoch: 0, Batch: 19, Loss: 0.9953, LR: 0.0000, Time: 0.3610 sec/it, Seq len: 8764.8, Slide ID: TCGA-55-A48Y-01Z-00-DX1.D8735347-E060-439F-B5A1-1E47A958A392.svs
Epoch: 0, Batch: 39, Loss: 0.8931, LR: 0.0000, Time: 0.3095 sec/it, Seq len: 9236.4, Slide ID: TCGA-05-4415-01Z-00-DX1.55E0C429-B308-4962-8DA9-41D7D3F7764E.svs
Epoch: 0, Batch: 59, Loss: 0.9053, LR: 0.0000, Time: 0.3087 sec/it, Seq len: 10212.0, Slide ID: TCGA-44-6779-01Z-00-DX1.40f10ad8-55f3-4043-a89b-37d33a26dd8c.svs
Epoch: 0, Batch: 79, Loss: 0.8811, LR: 0.0000, Time: 0.3020 sec/it, Seq len: 10281.0, Slide ID: TCGA-55-8619-01Z-00-DX1.46C7678A-6032-4C95-B535-85C87B92B6ED.svs
Epoch: 0, Batch: 99, Loss: 0.8543, LR: 0.0000, Time: 0.2964 sec/it, Seq len: 10177.1, Slide ID: TCGA-NJ-A4YI-01Z-00-DX1.C4111D01-27BF-486F-8E0E-C8053DB16133.svs
Epoch: 0, Batch: 119, Loss: 0.8049, LR: 0.0000, Time: 0.2946 sec/it, Seq len: 10321.7, Slide ID: TCGA-38-4625-01Z-00-DX1.ffdbfc1d-7a21-4e67-a54f-89597bd14a7f.svs
Epoch: 0, Batch: 139, Loss: 0.8149, LR: 0.0000, Time: 0.2974 sec/it, Seq len: 10669.9, Slide ID: TCGA-93-A4JN-01Z-00-DX1.ED4C9365-6CCF-4AEE-B4C9-3CC5EC57286C.svs
Epoch: 0, Batch: 159, Loss: 0.8097, LR: 0.0000, Time: 0.2954 sec/it, Seq len: 10612.3, Slide ID: TCGA-44-5643-01Z-00-DX1.83fb7631-0ecb-4473-bfb2-c8daa2f87d35.svs
Epoch: 0, Batch: 179, Loss: 0.8233, LR: 0.0001, Time: 0.2904 sec/it, Seq len: 10387.6, Slide ID: TCGA-44-3917-01Z-00-DX1.cf5b5b49-de5e-4f2e-90b4-b138f55560a9.svs
Epoch: 0, Batch: 199, Loss: 0.8139, LR: 0.0001, Time: 0.2893 sec/it, Seq len: 10447.0, Slide ID: TCGA-44-A47A-01Z-00-DX1.62448803-3A7B-41EC-9794-67916DA0792E.svs
Epoch: 0, Batch: 219, Loss: 0.7838, LR: 0.0001, Time: 0.2843 sec/it, Seq len: 10078.0, Slide ID: TCGA-86-8671-01Z-00-DX1.1fd0019c-df9d-48cc-9055-8de57759f273.svs
Epoch: 0, Batch: 239, Loss: 0.7757, LR: 0.0001, Time: 0.2861 sec/it, Seq len: 10212.0, Slide ID: TCGA-55-A4DF-01Z-00-DX1.C945E1AD-BEF4-403F-BB11-BAC831D24CDA.svs
Epoch: 0, Batch: 259, Loss: 0.7930, LR: 0.0001, Time: 0.2873 sec/it, Seq len: 10312.9, Slide ID: TCGA-49-6742-01Z-00-DX4.a11201e1-9eeb-40ea-9c88-28de847ef7d8.svs
Epoch: 0, Batch: 279, Loss: 0.7794, LR: 0.0001, Time: 0.2893 sec/it, Seq len: 10410.2, Slide ID: TCGA-75-5147-01Z-00-DX1.3156FA5C-9737-4EAA-989C-FD578FBF15A1.svs
Traceback (most recent call last):
  File "/workspace/opensource/prov-gigapath/finetune/main.py", line 82, in <module>
    val_records, test_records = train((train_loader, val_loader, test_loader), fold, args)
  File "/workspace/opensource/prov-gigapath/finetune/training.py", line 71, in train
    train_records = train_one_epoch(train_loader, model, fp16_scaler, optimizer, loss_fn, i, args)
  File "/workspace/opensource/prov-gigapath/finetune/training.py", line 128, in train_one_epoch
    logits = model(images, img_coords)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/opensource/prov-gigapath/gigapath/classification_head.py", line 81, in forward
    img_enc = self.slide_encoder.forward(images, coords, all_layer_embed=True)
  File "/workspace/opensource/prov-gigapath/gigapath/slide_encoder.py", line 208, in forward
    x_list = self.encoder(src_tokens=None, token_embeddings=x, return_all_hiddens=all_layer_embed)["encoder_states"]
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/opensource/prov-gigapath/gigapath/torchscale/model/../../torchscale/architecture/encoder.py", line 374, in forward
    x, l_aux_i = layer(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/opensource/prov-gigapath/gigapath/torchscale/model/../../torchscale/architecture/encoder.py", line 127, in forward
    x, _ = self.self_attn(
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/opensource/prov-gigapath/gigapath/torchscale/model/../../torchscale/component/dilated_attention.py", line 210, in forward
    attn = self.scattering(outs, lses, tgt_len, bsz, offset=offset)
  File "/workspace/opensource/prov-gigapath/gigapath/torchscale/model/../../torchscale/component/dilated_attention.py", line 110, in scattering
    o, lse = self.sparse_to_dense(o, lse, dr)
  File "/workspace/opensource/prov-gigapath/gigapath/torchscale/model/../../torchscale/component/dilated_attention.py", line 42, in sparse_to_dense
    out = rearrange(out, 'b l h d r1 r2 -> b (r2 h) (l r1) d', r1=ratio, r2=ratio)
  File "/opt/conda/lib/python3.10/site-packages/einops/einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
  File "/opt/conda/lib/python3.10/site-packages/einops/einops.py", line 523, in reduce
    return _apply_recipe(
  File "/opt/conda/lib/python3.10/site-packages/einops/einops.py", line 250, in _apply_recipe
    tensor = backend.reshape(tensor, final_shapes)
  File "/opt/conda/lib/python3.10/site-packages/einops/_backends.py", line 92, in reshape
    return x.reshape(shape)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 72.00 MiB (GPU 0; 39.59 GiB total capacity; 37.56 GiB already allocated; 14.19 MiB free; 38.21 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I use A100 gpu with 40g memory. The config is same as in run_panda.sh expect those data paths.

Thanks.

**Comment by HanwenXuTHU** [comment]
Hi Yihu, can you tell me which slide is causing this OOM? Or the longest sequence your dataset?

**Comment by yihu-dev** [comment]
Hi @HanwenXuTHU,

I ran this code through slides:
```
with torch.cuda.amp.autocast(dtype=torch.float16):
    y = model(features, coords, all_layer_embed=True)
```

 and found one slide cause the OOM: TCGA-J2-8192-01Z-00-DX1.A784F381-7906-480F-99A1-0B88005953A0.svs

**Comment by HanwenXuTHU** [comment]
Great, can you check the size of `features` for this slide?

**Comment by yihu-dev** [comment]
> Great, can you check the size of `features` for this slide?

features shape is torch.Size([45680, 1536])
coords.max(dim=1) gives: values=tensor([93952, 43776])

**Comment by HanwenXuTHU** [comment]
I test on our 80GB A100 memory and it worked well. The peak memory is near 39674MB, so it might throw out OOM when testing with 40GB A100. Can you also tell me if you are tiling at 20x level or 40x level?

**Comment by yihu-dev** [comment]
Yes, I use 20x level. The memory usage is 39916MB if I remove that slide.

**Comment by HanwenXuTHU** [comment]
Given your GPU memory constraint, I think a temporary approach might be shortening `max_tiles: 1000000` in the yaml config, this is not a perfect solution and will simply truncate the maximum sequence to the length you specified. In the long run, we are working on preparing the multi-GPU fine-tuning version, where researchers will not be limited by the single GPU memory size.

**Comment by yihu-dev** [comment]
Thanks! I close this issue.
